platformName=Windows 10
browserVersion=135

lt.geoLocation=IN
lt.visual=true
lt.video=true
lt.headless=false
lt.seCdp=false
lt.network=true
lt.timezone=Kolkata
lt.build=Weekly_Run
lt.project=LambdaTest_Sample_Project
lt.buildTags=Weekly
lt.name=Herokuapp_Ui_Automation
lt.tags=Smoke
lt.tunnel=false
lt.console=info
lt.networkThrottling=Regular 4G
lt.w3c=true